### ISSUE TITLE
Vague error upon startup - ubuntu 18.04, v0.24

### ISSUE THREAD

**Issue by royldean** [ac2cz/Falcon#48]
I'm getting this error.  Not sure if this is something simple or not.   This occurs after putting in my callsign and data folder location.   It gives me a couple of file placement errors, then this pops up and it's all over.
![pacsat_error](https://user-images.githubusercontent.com/36039589/62815271-53ef9c80-bae5-11e9-98dc-1c6949e717c7.png)

[edit]  I tried deleting the files as suggested in the error message, but that doesn't solve the issue.

**Comment by ac2cz** [comment]
Is this after an upgrade or at first install?  

This is a catchall error when something unexpected happened with the startup.  Usually it means a file is missing or old config files are used with a newer version or vice versa.

You could delete (or temporarily rename) the settings file called: ~/PacsatGroundConfig/PacSatGround.properties

If that does not work then try a fresh install, or at least replace all the config files in the install dir from a new install.  Specifically:
FalconsaSat-3.properties
spacecraft/*

**Comment by royldean** [comment]
This is a first install, zip pulled from your website (0.24).   Below is the file error I get before the final error shown above:
![pacsat_file_error](https://user-images.githubusercontent.com/36039589/62822595-c72ff780-bb53-11e9-8864-105a1feb0aea.png)

I've tried replacing all the config files, but that didn't change anything (they were identical, no?).

I wonder if this is some sort of folder permission problem?

**Comment by ac2cz** [comment]
Permissions look fine in the above screenshot.

How are you running the software?  Double clicking the jar file does not work on all flavors of Unix. The current directory needs to be the directory the jar file is in when you run it.  It should work from any directory, but the call to ask what directory the jar file is in does not seem to work on every platform.  So run it with a script that first changes directory into ~/pacsat or cd into ~/pacsat dir and run with java -jar PacSatGround.jar manually.

If that does not work (or you are already doing that) then try moving the data directory so that it is not inside the install directory. It looks like you have the software installed in ~/pacsat.  Try pointing the data directory to ~/pacsatdata or some other directory that is not install the install dir.

**Comment by royldean** [comment]
Tried the ~/pacsatdata data directory, same error.  :(

**Comment by ac2cz** [comment]
Ok, I reproduced this on 18.04.06.  Not sure why that is happening.  Others have run this on Linux before, but maybe the latest version only runs on Windows for some reason.  Let me investigate.

**Comment by ac2cz** [comment]
Try version 0.25 from my website.  I also made a linux build (which just swaps the exe for a start script).
https://www.g0kla.com/pacsat/PacSatGround_0.25_linux.tar.gz

Let me know if that fixes it

**Comment by royldean** [comment]
Yep, I've got the gui, now!   It still gave me the file error, but I assume that's just at startup...

Yes, just closed it and restarted (I'm using the script) and no file error this time.   I'll tinker with it some more today and see if I can't get positive results.  We've got a 36 degree FS3 pass in about 14 minutes.

**Comment by royldean** [comment]
Success!
![Screenshot from 2019-08-10 16-42-11](https://user-images.githubusercontent.com/36039589/62826737-d41e0c80-bb8e-11e9-8847-68619d982875.png)

I was just Rx'ing only (hooking up the transceiver is a little more involved, but hopefully I can try that in the coming days), but it appears that it successfully "talked" to Direwolf (even sending Tx commands, which Direwolf tried to transmit but just went into my ears as audio only).

I'll spend some time reading the manual and setting up the transceiver (not sure if I can go straight to the hardware TNC via KISS or use Direwolf as a middle man.... Direwolf may be easier to interface with.

Thanks!!!
