### ISSUE TITLE
Interruption of large file downloads

### ISSUE THREAD

**Issue by BX2ABT** [ac2cz/Falcon#79]
Scenario: the download of a very large file has been interrupted. 

Problem: with the next download request (DL SENDING: FILE REQ) the number of holes being requested to be filled is so large that that FS3 cannot read the incoming data stream because it is too long (my estimate is over 25 holes, but I'm not sure how to determine that). The result is that FS3 doesn't respond to these download requests at all and subsequently the file cannot be finished downloading.

Possible solution: limit the number of holes requested to be filled to maybe 20 or so. If these holes are filled then request the next batch of 20.

I hope I described the problem clearly. If not please tell me. Cheers. --Hans

**Comment by ac2cz** [comment]
Hans, thanks for the report.  I'm aware of the limitation of the uplink frame size and had attempted to limit the number of holes so that it fits.  But it looks like I have an error.  Is it possible that you have a kiss recording of the event?  That would help to debug.

**Comment by BX2ABT** [comment]
I tried with file 4abd (size: 196834) the last two days, constantly interrupting the download and this time I had no issues. I'll keep on doing this with other large files, so let's hope it will keep on working. Maybe you could downgrade the label to having less priority in the mean time.

**Comment by ac2cz** [comment]
No problem.  Marked low priority.  I know the issue but don't have live access to the sat right now so can't test.  We can monitor and see,  Maybe post a question to FS-3 and ask if others have seen the same issue?

**Comment by ac2cz** [comment]
Ok, in my code I have a comment that says "This will blow up if the hole list is too long" but then I never got around to implementing any code to handle that.  Oops.  

I think it is a rare situation though, because it is not based just on file size.  If you receive one block in the middle of a large file then you still only have 2 holes.  One hole for all the data before the part you received and one hole for all the data after that to the end of the file.  So you need to have received a lot of fragments to get a lot of holes.  But clearly it is possible.

The protocols are a bit ambiguous, but I understand that packet length is limited to 255 bytes on the spacecraft.  I had previously calculated that the maximum data length was 244 bytes and that 48 holes could fit, as each hole is 5 bytes.  But I don't know how I calculated it.  I have now set the limit at 45 and also actually check that we are less than that.  I calculate that as follows:

If we assume 255 bytes is the maximum length of the packet then:
- 3 bytes are consumed by the the KISS format
- UI frame has 16 byte header with a flag at each end and 2 byte CRC - 20 total consumed bytes
- So we are left with 255 -3 - 20 = 232 for data.  
- We then have the File Requset header which is 7 bytes (for the flags, fileId, block_size) leaving 225
- So 225 / 5 = 45

This could be another related issue though.  Each hole is 5 bytes long, consisting of the file offset (3 bytes) and the length of the hole (2 bytes).  So built into the protocol we can't support files longer than 24 bits - which is OK as that is 16MB - or holes that are longer than 16 bits, which is only 65k.  So it is entirely possible that you got a block or two in the middle of the 196,834 byte file and the holes were then longer than 65k.  So I think I need to limit the size of the holes that I request too. The chunks we are sent have a max size of 244 bytes, so I don't think it matters if we say we have one hole that is 100k long covering most of the file or that there are two holes each of 50k long.

**Comment by ac2cz** [comment]
You can test this using this new jar file: https://www.g0kla.com/pacsat/PacSatGround.jar

Note that I don't have a good way to test this currently.  So reports are welcome.

If you want the entire install it is here too:
https://www.g0kla.com/pacsat/PacSatGround_0.38.6_windows.zip
https://www.g0kla.com/pacsat/PacSatGround_0.38.6_linux.tar.gz

**Comment by BX2ABT** [comment]
> I think it is a rare situation though, because it is not based just on file size. If you receive one block in the middle of a large file then you still only have 2 holes. One hole for all the data before the part you received and one hole for all the data after that to the end of the file. So you need to have received a lot of fragments to get a lot of holes. But clearly it is possible.

It happens when the FS-3 signal is fading in and out, but more so when there is interference from local FM stations interrupting the download when having a QSO.
>
I have send you a log and kiss file from a session where a big file was interrupted several times and where the next download request had 41 hole requests.

73 de Hans

**Comment by ac2cz** [comment]
See https://www.g0kla.com/workbench/2021-02-27.php and https://www.g0kla.com/workbench/2021-03-07.php for how I fixed this.
You can download the test version here: https://www.g0kla.com/pacsat/index.php  Just the jar file will do.
